// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalPoint.Api;

#nullable disable

namespace RentalPoint.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241224154514_addSeed3")]
    partial class addSeed3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RentalPoint.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6f1e1d6-41f9-4b5e-9aeb-9d6b657b5c1a"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("b6ab5de6-8f1f-4dd4-8e14-b7f5b7e6c0ab"),
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("f8a7d5e4-1e8b-4d56-8a0a-8e5f6c7d7c8d"),
                            Name = "Tools"
                        },
                        new
                        {
                            Id = new Guid("b1c5e8a6-3f42-4c77-ae5c-1c9e1e4d3a8b"),
                            Name = "Outdoor"
                        },
                        new
                        {
                            Id = new Guid("b9c5e8a6-3f42-4c77-ae5c-1c9e1e4d3a8b"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("a3c8e5d5-3f42-4c77-ae5c-1c9e1e4d3b8e"),
                            Name = "Toys"
                        },
                        new
                        {
                            Id = new Guid("c5e8a1b6-4d7f-4b8e-9d6b-4c1e6b8a8f2c"),
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("RentalPoint.Api.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4a1b2c3-d4e5-6789-abcd-ef0123456789"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = new Guid("4b3e2a1c-5d6f-7890-a1b2-c3d4e5f67890"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "098-765-4321"
                        },
                        new
                        {
                            Id = new Guid("f9a8b7c6-d5e4-3f2a-1b0c-9e8f7a6b5c4d"),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PhoneNumber = "234-567-8901"
                        },
                        new
                        {
                            Id = new Guid("c1a2b3d4-e5f6-7890-a1b2-c3d4e5f67890"),
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            PhoneNumber = "345-678-9012"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0a1b-2c3d-4e5f6a7b8c9d"),
                            Email = "charlie.davis@example.com",
                            FirstName = "Charlie",
                            LastName = "Davis",
                            PhoneNumber = "456-789-0123"
                        },
                        new
                        {
                            Id = new Guid("f1e2d3c4-b5a6-7890-a1b2-c3d4e5f67890"),
                            Email = "diana.evans@example.com",
                            FirstName = "Diana",
                            LastName = "Evans",
                            PhoneNumber = "567-890-1234"
                        },
                        new
                        {
                            Id = new Guid("e1f2c3b4-a5d6-7890-b1c2-d3e4f5a6b7c8"),
                            Email = "edward.wilson@example.com",
                            FirstName = "Edward",
                            LastName = "Wilson",
                            PhoneNumber = "678-901-2345"
                        });
                });

            modelBuilder.Entity("RentalPoint.Api.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7a2b3c4-d5e6-7890-a1b2-c3d4e5f67890"),
                            Description = "New Year Discount",
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a4b2c3d4-e5f6-7890-a1b2-c3d4e5f67890"),
                            Description = "Summer Sale",
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b4c2d3e4-f5a6-7890-a1b2-c3d4e5f67890"),
                            Description = "Black Friday Deals",
                            EndDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c4d2e3f4-a5b6-7890-a1b2-c3d4e5f67890"),
                            Description = "Christmas Sale",
                            EndDate = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e7f2c3d4-b5c6-7890-a1b2-c3d4e5f67890"),
                            Description = "Spring Clearance",
                            EndDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f2a2b3c4-d5e6-7890-a1b2-c3d4e5f67890"),
                            Description = "Fall Specials",
                            EndDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b3c2d3e4-f5a6-7890-a1b2-c3d4e5f67890"),
                            Description = "Labor Day Sale",
                            EndDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RentalPoint.Api.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRented")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2b3c4d5-e6f7-89a0-b1c2-d3e4f5a6b7c8"),
                            CategoryId = new Guid("d6f1e1d6-41f9-4b5e-9aeb-9d6b657b5c1a"),
                            Description = "A high-performance laptop.",
                            IsRented = false,
                            Name = "Laptop",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-a1b2-c3d4e5f67890"),
                            CategoryId = new Guid("b6ab5de6-8f1f-4dd4-8e14-b7f5b7e6c0ab"),
                            Description = "A comfortable office chair.",
                            IsRented = false,
                            Name = "Chair",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-7890-a1b2-c3d4e5f67890"),
                            CategoryId = new Guid("f8a7d5e4-1e8b-4d56-8a0a-8e5f6c7d7c8d"),
                            Description = "A powerful electric drill.",
                            IsRented = false,
                            Name = "Drill",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-a6f7-89a0-b1c2-d3e4f5a6b7c8"),
                            CategoryId = new Guid("b1c5e8a6-3f42-4c77-ae5c-1c9e1e4d3a8b"),
                            Description = "A waterproof camping tent.",
                            IsRented = false,
                            Name = "Tent",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = new Guid("e1f2c3a4-b5c6-7890-a1b2-c3d4e5f67890"),
                            CategoryId = new Guid("b9c5e8a6-3f42-4c77-ae5c-1c9e1e4d3a8b"),
                            Description = "A regulation soccer ball.",
                            IsRented = false,
                            Name = "Soccer Ball",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = new Guid("f2b3c4d5-e5f6-7890-a1b2-c3d4e5f67890"),
                            CategoryId = new Guid("a3c8e5d5-3f42-4c77-ae5c-1c9e1e4d3b8e"),
                            Description = "A collectible action figure.",
                            IsRented = false,
                            Name = "Action Figure",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = new Guid("c2d3e4f5-a6b7-8901-a1b2-c3d4e5f67890"),
                            CategoryId = new Guid("c5e8a1b6-4d7f-4b8e-9d6b-4c1e6b8a8f2c"),
                            Description = "A cookbook for home chefs.",
                            IsRented = false,
                            Name = "Cookbook",
                            Price = 30.00m
                        });
                });

            modelBuilder.Entity("RentalPoint.Api.Models.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("ItemIsBacked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ItemId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7a2b3c4-d5e6-7890-a1b2-c3d4e5f67891"),
                            ClientId = new Guid("f4a1b2c3-d4e5-6789-abcd-ef0123456789"),
                            ItemId = new Guid("a1b2c3d4-e5f6-7890-a1b2-c3d4e5f67890"),
                            ItemIsBacked = false
                        },
                        new
                        {
                            Id = new Guid("f7a2b3c4-d5e6-7890-a1b2-c3d4e5f67892"),
                            ClientId = new Guid("c1a2b3d4-e5f6-7890-a1b2-c3d4e5f67890"),
                            ItemId = new Guid("a1b2c3d4-e5f6-7890-a1b2-c3d4e5f67890"),
                            ItemIsBacked = false
                        },
                        new
                        {
                            Id = new Guid("f7a2b3c4-d5e6-7890-a1b2-c3d4e5f67893"),
                            ClientId = new Guid("4b3e2a1c-5d6f-7890-a1b2-c3d4e5f67890"),
                            ItemId = new Guid("e1f2c3a4-b5c6-7890-a1b2-c3d4e5f67890"),
                            ItemIsBacked = false
                        });
                });

            modelBuilder.Entity("RentalPoint.Api.Models.Item", b =>
                {
                    b.HasOne("RentalPoint.Api.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RentalPoint.Api.Models.Rental", b =>
                {
                    b.HasOne("RentalPoint.Api.Models.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalPoint.Api.Models.Item", "Item")
                        .WithMany("Rentals")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RentalPoint.Api.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RentalPoint.Api.Models.Client", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("RentalPoint.Api.Models.Item", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
